######################################################################
# Automatically generated by qmake (2.01a) Do. Jun 2 10:55:57 2016
######################################################################
TEMPLATE = app
TARGET = Game
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets multimedia

# Input
HEADERS += spiel.h 
SOURCES += main.cpp spiel.cpp

RESOURCES += game.qrc
