######################################################################
# Automatically generated by qmake (2.01a) Do. Jun 2 10:55:57 2016
######################################################################
TEMPLATE = app
TARGET = Spiel_geruest
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += spiel.h 
SOURCES += main.cpp spiel.cpp
